apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-landing-page
  description: Demo website created by Backstage template
  tags:
    - website
spec:
  type: website
  owner: thuyle96123456
  lifecycle: experimental
